/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_HELLOWORLD_PB_H_INCLUDED
#define PB_HELLOWORLD_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _sayhello {
    pb_callback_t greeting;
    uint32_t n;
} sayhello;


/* Initializer values for message structs */
#define sayhello_init_default                    {{{NULL}, NULL}, 0}
#define sayhello_init_zero                       {{{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define sayhello_greeting_tag                    1
#define sayhello_n_tag                           2

/* Struct field encoding specification for nanopb */
#define sayhello_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   greeting,          1) \
X(a, STATIC,   SINGULAR, UINT32,   n,                 2)
#define sayhello_CALLBACK pb_default_field_callback
#define sayhello_DEFAULT NULL

extern const pb_msgdesc_t sayhello_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define sayhello_fields &sayhello_msg

/* Maximum encoded size of messages (where known) */
/* sayhello_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
