# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='helloworld.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10helloworld.proto\"\'\n\x08sayhello\x12\x10\n\x08greeting\x18\x01 \x01(\t\x12\t\n\x01n\x18\x02 \x01(\rb\x06proto3'
)




_SAYHELLO = _descriptor.Descriptor(
  name='sayhello',
  full_name='sayhello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='sayhello.greeting', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='n', full_name='sayhello.n', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['sayhello'] = _SAYHELLO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

sayhello = _reflection.GeneratedProtocolMessageType('sayhello', (_message.Message,), {
  'DESCRIPTOR' : _SAYHELLO,
  '__module__' : 'helloworld_pb2'
  # @@protoc_insertion_point(class_scope:sayhello)
  })
_sym_db.RegisterMessage(sayhello)


# @@protoc_insertion_point(module_scope)
